# Note: right now we don't use go-specific features of travis.
# Later we might automate "go test" etc. (or do it inside a docker container...?)

language: go

# This should match the version in the Dockerfile.
go: 1.2.1

# Let us have pretty experimental Docker-based Travis workers.
# (These spin up much faster than the VM-based ones.)
sudo: false

# Disable the normal go build.
install: true

before_script:
  - env | sort

script:
  - hack/make.sh validate-dco
  - hack/make.sh validate-gofmt

# vim:set sw=2 ts=2:
